### ISSUE TITLE
[feature] custom text for title screen & message prompts

### ISSUE THREAD

**Issue by minotalen** [Auroriax/PuzzleScriptPlus#10]
![grafik](https://user-images.githubusercontent.com/29110130/142036846-ad20a80f-ed7c-4a25-8823-1249fa727c6e.png)

When using mouse interaction the title screen texts change to focus on mouse interaction.
I'd like to suggest 3 prelude options: `text_titleA`, `text_titleB` and `text_message`. They would replace the original text, it would be necessary to limit the character count.

My current method is going into the html export and manually replacing the texts..

**Comment by Auroriax** [comment]
![afbeelding](https://user-images.githubusercontent.com/6784890/165955203-1544092e-2859-4cb0-8356-464f00fee560.png)

![afbeelding](https://user-images.githubusercontent.com/6784890/165955259-b7e9359c-49e8-4b7c-93de-a4b657924003.png)
