### ISSUE TITLE
[feature] highlight line breaks in messages, align text

### ISSUE THREAD

**Issue by minotalen** [Auroriax/PuzzleScriptPlus#11]
For most of my PS games I've been meticulously aligning my messages with trial-and-error. It'd be super helpful to me if there was a prelude option `message_align` that could be set to `center`(standard), `left` and `right`, with the option to realtime_twiddle during runtime.

Having a visual indicator for where a line breaks in messages happen would be super neat QOL as well (maybe a blue vertical line `|`?).

**Comment by Auroriax** [comment]
(Note to self: adding newlines using `\n` was implemented in the Conveyor Confusion PS fork by Joseph Mansfield... see conversation on the Thinky Puzzlescript discord here: https://discord.com/channels/473538592896188446/603626559189942294/952545481781825558 )

I've also looked into adding message_align and it sound like a solid addition that I'll probably pick up once I have some time for it!

**Comment by Auroriax** [comment]
So sorry for the delay, but this is now coming up in the next version of PS+!
- You can use \n to denote a newline.
- You can use the MESSAGE_TEXT_ALIGN prelude param to align messages to LEFT, CENTER (default), or RIGHT. Can be twiddled at runtime.
