### ISSUE TITLE
URL creation should not be stopped because of warnings

### ISSUE THREAD

**Issue by Monakrom** [Auroriax/PuzzleScriptPlus#114]
Check ([ ] -> [x]) all that apply, then describe the issue below:

- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

The URL compiler says "Cannot link directly to playable game, because there are compiler errors." even when there are only warnings and no errors. For example, when trying to create a link to a playable build where both tweening and late rules exist, you will be stopped with the aforementioned message. This also means you cannot use brackets as symbols in level ascii, or have even slight inconsistencies in code, such as irregularly sized levels and the like. 

More likely than not, the developer of the game is very aware of warnings in the console, and has decided that they are unimportant, at least for the time being. 

With all of that in mind I feel like this is unnecessarily rigid, and links to playable games should be allowed even when there are warnings visible in the console, which is how it is in regular Puzzlescript.

**Comment by Monakrom** [comment]
Missed a closed issue on it. Still think it’s a problem though.

**Comment by david-pfx** [comment]
This is not the cause. There is a long-standing bug in PS+ whereby warnings get counted as errors. I'll raise an issue.

**Comment by Monakrom** [comment]
> This is not the cause. There is a long-standing bug in PS+ whereby warnings get counted as errors. I'll raise an issue.

Ahh ok. Didn’t know that. That certainly explains it.

**Comment by david-pfx** [comment]
Yes, I've now checked it and it does seem that #115 is the cause of this problem.
