### ISSUE TITLE
mobile + level_select + mouse_left crashes on level select screen

### ISSUE THREAD

**Issue by pancelor** [Auroriax/PuzzleScriptPlus#35]
hello! I'm trying to debug why https://pancelor.itch.io/like-a-hot-knife-through-butter crashes on mobile in the level select screen

I was able to get [android remote debugging](https://firefox-source-docs.mozilla.org/devtools-user/remote_debugging/firefox_for_android/index.html) sort of set up. I don't really know what I'm doing, but I was able to get a stack trace of a crash! It ends with `getTilesTraversingPoints` (in src/js/inputoutput.js) but the code is minified and this dev setup I have is pretty awful so I haven't been able to dig much deeper

Here's the stack trace, from firefox mobile:
```
Script terminated by timeout at:
getTilesTraversingPoints@https://v6p9d9t4.ssl.hwcdn.net/html/5770877/index.html:11946:5502
mouseAction@https://v6p9d9t4.ssl.hwcdn.net/html/5770877/index.html:11946:8753
mouseMove@https://v6p9d9t4.ssl.hwcdn.net/html/5770877/index.html:11946:12629
EventListener.handleEvent*@https://v6p9d9t4.ssl.hwcdn.net/html/5770877/index.html:11946:19526
```

you can crash my game pretty reliably by going to the level select menu, pressing on the screen for ~0.5 seconds and then swiping (well, it crashes mobile chrome; on mobile firefox it hangs for a minute and then starts working again.)

-----

## more info / theories

I noticed by messing around with basic puzzlescriptplus examples that the mobile menu behavior in my game is very odd - if you make a game with `level_select` and no `mouse_left`, you can swipe in the menu to move the selection cursor around and tap to activate the cursor (like a simulated keyboard) but in my game (which has level_select and also mouse_left) the mobile controls in the level select menu act more like a mouse rather than a simulated keyboard -- you can click on things directly. This is pretty weird and feels wrong, and I bet it's related to this crash.

I think the combination of `level_select` and `mouse_left` in the prelude is causing `getTilesTraversingPoints` to get called differently than it should be (maybe it shouldn't be called at all?) and it's entering some sort of infinite loop, probably because the level select screen doesn't have a normal grid like actual levels.

my game does use a custom fork of puzzlescriptplus (mine deals with sprites larger than the grid size; I haven't published it anywhere b/c it's quite janky. see my [devlog](https://pancelor.itch.io/like-a-hot-knife-through-butter/devlog/381571/a-peek-into-the-kitchen) for more details) but I don't think that's relevant.

**Comment by Auroriax** [comment]
It seems commit 6642ecf has fixed the crash after level select (confirmed via Chrome Remote Debug via Android). I noticed that the crash only happens the 2nd time you pick a level from the level select. And it seems the dragging state is not correctly resetted in-between levels, causing the program to look for a drag when there wasn't one. I'm not sure why this affected only mobile and not desktop.

@pancelor would you be able to confirm if this resolves the crash on your side? It is a simple fix so you should have no issues to integrate it into your fork of the engine :)

Regarding the menu issue, personally I really like the mouse-like behavior and it was a conscious design decision to implement it like that. I think your argument is good however, and I've added it to #36 to add a prelude flag for toggling it.

Cheers!

**Comment by pancelor** [comment]
thank you for the quick fix! I just got back from vacation and changed those two lines in my fork, and it fixed my issue \o/

fyi someone in the comments found another weird crash in the game; I have no idea how it's happening and don't plan to look into it. it's [here](https://itch.io/post/5925685) if you're curious (but like, I'm not expecting it to be fixed -- just thought you might want to know)

ahh I didn't realize the mouse-like behavior was a conscious choice... I think it would help me if there was some sort of "css :hover" style applied to anything clickable. i.e, when you're hovering over a menu option if the selection cursors (the `#`s) moved to where you're currently hovering. that's my 2 cents on what I think would feel good there

anyway, thanks again!

**Comment by Auroriax** [comment]
Thanks for getting back to me to confirm the fix! I've also carded up the bug report and suggestion.
