### ISSUE TITLE
Documentation is unchanged from vanilla PuzzleScript in several places

### ISSUE THREAD

**Issue by Draknek** [Auroriax/PuzzleScriptPlus#67]
- Currently the GitHub link in the documentation goes to vanilla Puzzlescript, but it should probably link here
- At the top it says "PuzzleScript" not "PuzzleScript+"
- The about page is unchanged from vanilla PuzzleScript
- The credits page is unchanged from vanilla PuzzleScript
- The "Sponsor" link is ambiguous which project it's referring to - might be good to rename it "Sponsor PuzzleScript" or "Sponsor increpare"

**Comment by Auroriax** [comment]
Thanks for reporting, I completely agree on all counts and have clarified the documentation.
